controller_list:
  - name: fake_leftarm_controller
    type: $(arg execution_type)
    joints:
      - leftarm_shoulder_pan_joint
      - leftarm_shoulder_lift_joint
      - leftarm_elbow_joint
      - leftarm_wrist_1_joint
      - leftarm_wrist_2_joint
      - leftarm_wrist_3_joint
  - name: fake_rightarm_controller
    type: $(arg execution_type)
    joints:
      - rightarm_shoulder_pan_joint
      - rightarm_shoulder_lift_joint
      - rightarm_elbow_joint
      - rightarm_wrist_1_joint
      - rightarm_wrist_2_joint
      - rightarm_wrist_3_joint
  - name: fake_leftarm_hand_controller
    type: $(arg execution_type)
    joints:
      - leftarm_hande_left_finger_joint
  - name: fake_rightarm_hand_controller
    type: $(arg execution_type)
    joints:
      - rightarm_hande_left_finger_joint
initial:  # Define initial robot poses.
  - group: rightarm
    pose: home
  - group: leftarm
    pose: home