# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: rightarm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 500
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - leftarm_shoulder_pan_joint
    - leftarm_shoulder_lift_joint
    - leftarm_elbow_joint
    - leftarm_wrist_1_joint
    - leftarm_wrist_2_joint
    - leftarm_wrist_3_joint
    - rightarm_shoulder_pan_joint
    - rightarm_shoulder_lift_joint
    - rightarm_elbow_joint
    - rightarm_wrist_1_joint
    - rightarm_wrist_2_joint
    - rightarm_wrist_3_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 500
controller_list:
  - name: leftarm/scaled_pos_joint_traj_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - leftarm_shoulder_pan_joint
      - leftarm_shoulder_lift_joint
      - leftarm_elbow_joint
      - leftarm_wrist_1_joint
      - leftarm_wrist_2_joint
      - leftarm_wrist_3_joint
  - name: rightarm/scaled_pos_joint_traj_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - rightarm_shoulder_pan_joint
      - rightarm_shoulder_lift_joint
      - rightarm_elbow_joint
      - rightarm_wrist_1_joint
      - rightarm_wrist_2_joint
      - rightarm_wrist_3_joint